# Generated by Django 3.2.9 on 2021-11-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrationapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloud_connect',
            name='cloudUser',
        ),
        migrations.RemoveField(
            model_name='cloud_connect',
            name='password',
        ),
        migrations.AddField(
            model_name='cloud_connect',
            name='cloudServiceKeyLoc',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
