# Generated by Django 3.2.9 on 2021-11-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrationapp', '0002_auto_20211118_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloud_connect',
            name='projectName',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AlterField(
            model_name='cloud_connect',
            name='cloudName',
            field=models.CharField(choices=[('gcp', 'Google Cloud Platform'), ('aws', 'Amazon Workspace'), ('azure', 'Microsoft Azure')], default='gcp', max_length=50),
        ),
    ]
