# Generated by Django 3.2.9 on 2021-11-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrationapp', '0003_auto_20211118_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloud_connect',
            name='projectName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
